#db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

jwt:
  secret: "1234"